---
- name: Open k3s firewall ports on server nodes
  hosts: k3s-server
  become: true
  tasks:
    - name: Open k3s server ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "6443/tcp"          
        - "8472/udp"          
        - "10250/tcp"         
        - "30000-32767/tcp"   

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload
      changed_when: true

- name: Open k3s firewall ports on agent nodes
  hosts: k3s-agent
  become: true
  tasks:
    - name: Open k3s agent ports
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "8472/udp"          
        - "10250/tcp"         
        - "30000-32767/tcp"   

    - name: Reload firewalld
      ansible.builtin.command: firewall-cmd --reload
      changed_when: true
