FROM quay.io/fedora/fedora-bootc:44 AS base
RUN dnf install -y dnf5-plugins && \
    dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo && \
    dnf install -y \
        bash-completion \
        chrony \
        cloud-init \
        firewalld \
        git \
        jq \
        python3 \
        python3-cryptography \
        python3-firewall \
        python3-passlib \
        qemu-guest-agent \
        tailscale \
        vim \
        vim-enhanced \
        yq && \
    dnf clean all
# CIS hardening
RUN dnf install -y openscap-scanner scap-security-guide && \
    oscap xccdf eval --remediate \
        --profile xccdf_org.ssgproject.content_profile_standard \
        /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml ; \
    dnf remove -y openscap-scanner scap-security-guide && \
    dnf clean all
# Crypto policy
RUN update-crypto-policies --set DEFAULT
# SELinux kernel args
RUN mkdir -p /usr/lib/bootc/kargs.d
COPY kargs.d/01-selinux.toml /usr/lib/bootc/kargs.d/01-selinux.toml
# SELinux lockdown service
COPY selinux/selinux-lockdown.service /usr/lib/systemd/system/selinux-lockdown.service
# Enable services 
RUN systemctl enable \
    chronyd.service \
    firewalld.service \
    qemu-guest-agent.service \
    selinux-lockdown.service \
    tailscaled.service

RUN bootc container lint

# K3s server
FROM base AS k3s-server

RUN --mount=type=secret,id=K3S_TOKEN \
    K3S_TOKEN=$(cat /run/secrets/K3S_TOKEN) \
    curl -sfL https://get.k3s.io | \
    K3S_TOKEN=${K3S_TOKEN} \
    INSTALL_K3S_SKIP_ENABLE=true \
    INSTALL_K3S_SKIP_SELINUX_RPM=true \
    INSTALL_K3S_SELINUX_WARN=true \
    sh -
RUN systemctl enable k3s.service
RUN bootc container lint


FROM base AS k3s-agent

RUN --mount=type=secret,id=K3S_TOKEN \
    K3S_TOKEN=$(cat /run/secrets/K3S_TOKEN) \
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://192.168.50.220:6443 \
    K3S_TOKEN=${K3S_TOKEN} \
    INSTALL_K3S_SKIP_ENABLE=true \
    INSTALL_K3S_SKIP_SELINUX_RPM=true \
    INSTALL_K3S_SELINUX_WARN=true \
    sh -
RUN systemctl enable k3s-agent.service
RUN bootc container lint
